# Generated by Django 3.2.3 on 2025-07-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20250719_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите теги', related_name='tags', to='recipes.Tag', verbose_name='Теги'),
        ),
    ]
